Repository sledilnik/website, pull requests merged in 2020-07, with the labels that each got.

#387 Age groups timeline visualization
  TODO.md
  src/locales/en.json
  src/locales/hr.json
  src/locales/sl.json
  src/visualizations/AgeGroupsTimelineViz/Analysis.fs
  src/visualizations/AgeGroupsTimelineViz/LowCharts.fs
  src/visualizations/AgeGroupsTimelineViz/Rendering.fs
  src/visualizations/AgeGroupsTimelineViz/Synthesis.fs
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/ShareButton.fs
  src/visualizations/Types.fs
  src/visualizations/Utils.fs
  tests/Visualizations.Tests/AgeGroupsTimelineTests/Calculating cases by age for day.fs
  tests/Visualizations.Tests/AgeGroupsTimelineTests/Calculating cases by age timeline.fs
  tests/Visualizations.Tests/AgeGroupsTimelineTests/Sythensizing data.fs
  tests/Visualizations.Tests/AgeGroupsTimelineTests/TestHelpers.fs
  tests/Visualizations.Tests/Visualizations.Tests.fsproj
Labels: WIP, deploy-preview

#390 refac to common data in tooltip
  src/App.vue
  src/components/Notice.vue
  src/locales/en.json
  src/locales/sl.json
  src/style/visualizations/main.sass
  src/visualizations/AgeGroupsTimelineViz/Synthesis.fs
  src/visualizations/EuropeMapChart.fs
Labels: deploy-preview

#417 Crosshair on y-axis
  src/visualizations/CountriesChartViz/Rendering.fs
  src/visualizations/Highcharts.fs
  src/visualizations/SpreadChart.fs
  src/visualizations/TestsChart.fs
Labels: deploy-preview

#431 Removed unused npm modules
  package-lock.json
  package.json
  yarn.lock
Labels: deploy-preview

#444 Static content organized by languages
  src/content/en/about.md
  src/content/en/datasources.md
  src/content/en/faq.md
  src/content/en/links.md
  src/content/en/models.md
  src/content/en/sources.md
  src/content/en/team.md
  src/content/sl/about.md
  src/content/sl/datasources.md
  src/content/sl/faq.md
  src/content/sl/links.md
  src/content/sl/models.md
  src/content/sl/sources.md
  src/content/sl/team.md
  src/router.js
Labels: deploy-preview

#442 Navbar: language chooser with full language names
  package.json
  src/components/Navbar.vue
  src/main.js
  yarn.lock
Labels: deploy-preview

#443 Added Croatian + German static pages and enabled translations
  src/components/Navbar.vue
  src/components/cards/InfoCard.vue
  src/content/de/about.md
  src/content/de/datasources.md
  src/content/de/faq.md
  src/content/de/links.md
  src/content/de/models.md
  src/content/de/sources.md
  src/content/de/team.md
  src/content/hr/about.md
  src/content/hr/datasources.md
  src/content/hr/faq.md
  src/content/hr/links.md
  src/content/hr/models.md
  src/content/hr/sources.md
  src/content/hr/team.md
  src/i18n.js
  src/router.js
  src/visualizations/_highcharts.js
Labels: deploy-preview

#453 Show GitHub button in header on larger displays
  src/components/Navbar.vue
Labels: deploy-preview

#452 Age groups timeline active
  TODO.md
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/sl.json
  src/visualizations/AgeGroupsTimelineViz/Analysis.fs
  src/visualizations/AgeGroupsTimelineViz/Rendering.fs
  src/visualizations/AgeGroupsTimelineViz/Synthesis.fs
  src/visualizations/App.fsproj
  src/visualizations/Days.fs
  src/visualizations/Statistics.fs
  src/visualizations/Utils.fs
  tests/Visualizations.Tests/AgeGroupsTimelineTests/Calculating cases by age timeline.fs
  tests/Visualizations.Tests/AgeGroupsTimelineTests/Sythensizing data.fs
  tests/Visualizations.Tests/AgeGroupsTimelineTests/Working with dated arrays.fs
  tests/Visualizations.Tests/Calculating windowed sums.fs
  tests/Visualizations.Tests/Date arithmetic.fs
  tests/Visualizations.Tests/Visualizations.Tests.fsproj
Labels: .NET, WIP, deploy-preview, enhancement

#454 Active cases with up/down arrows
  src/components/cards/InfoCard.vue
  src/pages/StatsPage.vue
Labels: deploy-preview

#468 Green & red country list update
  src/visualizations/EuropeMapChart.fs
Labels: deploy-preview

#470 Input date parser, fix credits
  src/visualizations/AgeGroupsChart.fs
  src/visualizations/Highcharts.fs
Labels: deploy-preview

#476 Language chooser: full name on large screens
  src/components/Navbar.vue
Labels: deploy-preview

#480 Enabled italian translation
  src/content/en/team.md
  src/content/it/about.md
  src/content/it/datasources.md
  src/content/it/faq.md
  src/content/it/links.md
  src/content/it/models.md
  src/content/it/sources.md
  src/content/it/team.md
  src/content/sl/team.md
  src/i18n.js
  src/router.js
  src/visualizations/Highcharts.fs
Labels: deploy-preview

#391 Allow country-specific translations by setting the country context to some i18next calls
  .env
  src/i18n.js
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/me.json
  src/locales/mk.json
  src/locales/sl.json
  src/locales/sq.json
  src/pages/EmbedMakerPage.vue
  src/visualizations/App.fs
Labels: deploy-preview
