Repository sledilnik/website, pull requests merged in 2020-10, with the labels that each got.

#571 Youtube animation page
  src/components/Footer.vue
  src/components/Loader.vue
  src/components/Navbar.vue
  src/components/Youtube.vue
  src/components/cards/Card.vue
  src/components/cards/CardData.vue
  src/components/cards/InfoCard.vue
  src/components/tables/AgeGroupsFemales.vue
  src/components/tables/AgeGroupsMales.vue
  src/components/tables/RegionalOverview.vue
  src/components/tables/TestsInfections.vue
  src/embed.js
  src/embed/Card.vue
  src/embed/InfoCard.vue
  src/locales/en.json
  src/locales/sl.json
  src/main.js
  src/pages/AnimationPage.vue
  src/pages/StatsPage.vue
  src/pages/TablesPage.vue
  src/store/stats.store.js
  src/style/visualizations/embeded.sass
  src/style/visualizations/main.sass
Labels: deploy-preview

#586 Incidence infocard
  src/components/cards/InfoCard.vue
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/sl.json
  src/pages/StatsPage.vue
  src/style/main.scss
Labels: WIP, deploy-preview

#594 #581 MetricsComparison: 7 day moving average
  TODO.md
  src/locales/sl.json
  src/visualizations/CountriesChartViz/Analysis.fs
  src/visualizations/MetricsComparisonChart.fs
Labels: .NET, WIP, deploy-preview, enhancement, priority-1

#597 Yt municipality video on home page
  src/components/Youtube.vue
  src/components/cards/Card.vue
  src/pages/StatsPage.vue
Labels: deploy-preview

#574 Weekly Stats
  package.json
  src/components/Notice.vue
  src/content/sl/faq.md
  src/i18n.js
  src/locales/en.json
  src/locales/sl.json
  src/style/visualizations/main.sass
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/EuropeMapChart.fs
  src/visualizations/Highcharts.fs
  src/visualizations/ShareButton.fs
  src/visualizations/SourcesChart.fs
  src/visualizations/Types.fs
  src/visualizations/data/WeeklyStats.fs
  tests/unit/i18n.spec.js
  yarn.lock
Labels: deploy-preview

#590 Ostanizdrav integracija vizualiziacij
  package.json
  src/components/Navbar.vue
  src/components/Notice.vue
  src/components/Youtube.vue
  src/locales/en.json
  src/locales/sl.json
  src/pages/OstaniZdravPage.vue
  src/pages/StatsPage.vue
  src/router.js
  src/style/main.scss
  src/style/visualizations/main.sass
  src/vega/published.js
  src/vega/publishedByRisk.js
  src/vega/userPublishedByCount.js
  src/vega/usercount.js
  src/vega/valid.js
  src/vega/validByRisk.js
  yarn.lock
Labels: deploy-preview

#613 Fix legend behavior on maps
  src/visualizations/_highcharts.js
Labels: deploy-preview

#616 Margin between icons on small screens
  src/components/cards/InfoCard.vue
Labels: deploy-preview

#611 Changed color scale on regions/municipalities map
  src/content/en/team.md
  src/content/sl/team.md
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/sl.json
  src/locales/sq.json
  src/visualizations/MapChart.fs
Labels: deploy-preview

#615 Switched Countries charts to show per 100k
  TODO.md
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/it.json
  src/locales/mk.json
  src/locales/sl.json
  src/locales/sq.json
  src/visualizations/CountriesChartViz/Analysis.fs
  src/visualizations/CountriesChartViz/Rendering.fs
  src/visualizations/EuropeMapChart.fs
  tests/Visualizations.Tests/CountriesChartTests/Grouping OWID data by countries.fs
Labels: .NET, WIP, deploy-preview, enhancement

#619 Corrections to the regions/municipalities color scheme
  src/visualizations/MapChart.fs
Labels: deploy-preview

#617 Switch to CSV municipalities
  src/embed/Chart.vue
  src/pages/StatsPage.vue
  src/pages/WorldStatsPage.vue
  src/store/health-centers.store.js
  src/store/hospitals.store.js
  src/store/index.js
  src/store/municipalities.store.js
  src/store/patients.store.js
  src/store/stats.store.js
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/Main.fs
  src/visualizations/Types.fs
  src/visualizations/data/Regions.fs
Labels: deploy-preview

#621 Mini graphs on Slovenian maps
  src/style/visualizations/main.sass
  src/visualizations/MapChart.fs
Labels: WIP, deploy-preview

#628 CSV health centers
  src/visualizations/App.fs
  src/visualizations/HCentersChart.fs
  src/visualizations/Utils.fs
  src/visualizations/data/HCenters.fs
  src/visualizations/data/Regions.fs
Labels: deploy-preview

#629 Regions/municipalities chart with a weekly relative increase indicator
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/MapChart.fs
Labels: deploy-preview

#620 Floating navigation menu
  package.json
  src/assets/svg/floating-close.svg
  src/assets/svg/floating-open.svg
  src/components/FloatingMenu.vue
  src/components/LanguageSwitcher.vue
  src/components/Navbar.vue
  src/index.js
  src/locales/en.json
  src/locales/sl.json
  src/main.js
  src/pages/StatsPage.vue
  src/pages/WorldStatsPage.vue
  src/visualizations/CasesChart.fs
  yarn.lock
Labels: deploy-preview

#638 Floating menu with icons
  src/assets/svg/graf.svg
  src/assets/svg/stolpicni.svg
  src/assets/svg/zemljevid.svg
  src/components/FloatingMenu.vue
  src/locales/sl.json
  src/style/visualizations/main.sass
  src/visualizations/App.fs
Labels: deploy-preview

#639 Renamed "Relative" to "Population Share" in the AgeGroups chart
  src/content/sl/faq.md
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/sl.json
  src/visualizations/AgeGroupsChart.fs
Labels: deploy-preview

#640 New colors for world map
  src/visualizations/EuropeMapChart.fs
  src/visualizations/MapChart.fs
Labels: deploy-preview

#642 Embeddable charts for #OstaniZdrav
  src/components/charts/VegaChart.vue
  src/components/charts/ostanizdrav/PublishedByRiskChart.vue
  src/components/charts/ostanizdrav/PublishedChart.vue
  src/components/charts/ostanizdrav/UserCountChart.vue
  src/components/charts/ostanizdrav/UserPublishedByCountChart.vue
  src/components/charts/ostanizdrav/ValidByRiskChart.vue
  src/components/charts/ostanizdrav/ValidChart.vue
  src/embed/Chart.vue
  src/pages/EmbedMakerPage.vue
  src/pages/OstaniZdravPage.vue
  src/vega/opts.js
Labels: deploy-preview

#644 Country charts: new and updated country sets
  Owid.Analyzer/Owid.Analyzer.fsproj
  Owid.Analyzer/Program.fs
  SloCovid19Website.sln
  TODO.md
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/it.json
  src/locales/mk.json
  src/locales/sl.json
  src/locales/sq.json
  src/visualizations/CountriesChartViz/CountrySets.fs
Labels: .NET, WIP, deploy-preview, enhancement

#645 Column chart in tooltip on regions/municipalities map
  src/style/visualizations/main.sass
  src/visualizations/Highcharts.fs
  src/visualizations/MapChart.fs
  src/visualizations/_highcharts.js
Labels: deploy-preview

#660 Daily Comparison: add hospital admitted/discharged and deaths
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/DailyComparisonChart.fs
Labels: deploy-preview

#661 increase tooltip data range to 60d
  src/visualizations/MapChart.fs
Labels: deploy-preview

#662 Add phase diagrams
  package.json
  src/components/FloatingMenu.vue
  src/embed/Chart.vue
  src/locales/en.json
  src/locales/sl.json
  src/style/visualizations/main.sass
  src/style/visualizations/slider.sass
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/Components/Slider.fs
  src/visualizations/Highcharts.fs
  src/visualizations/PhaseDiagram/Chart.fs
  src/visualizations/PhaseDiagram/Data.fs
  src/visualizations/PhaseDiagram/Types.fs
  src/visualizations/ShareButton.fs
  src/visualizations/Types.fs
  src/visualizations/Utils.fs
  yarn.lock
Labels: deploy-preview

#659 Relative increase and weekly incidence for world map
  src/locales/en.json
  src/locales/sl.json
  src/style/visualizations/main.sass
  src/visualizations/EuropeMapChart.fs
Labels: deploy-preview

#668 Ostanizdrav timestamp
  src/components/TimeStamp.vue
  src/pages/OstaniZdravPage.vue
  src/pages/StatsPage.vue
  src/pages/WorldStatsPage.vue
  src/services/api.service.js
  src/store.js
  src/store/index.js
  src/store/ostanizdrav.store.js
  src/store/patients.store.js
  src/store/stats.store.js
  src/style/index.scss
  tests/unit/store.spec.js
Labels: deploy-preview
