Repository sledilnik/website, pull requests merged in 2020-11, with the labels that each got.

#669 Care Patients chart
  examples/README.md
  examples/embed.html
  examples/embed_multi.html
  src/components/FloatingMenu.vue
  src/locales/en.json
  src/locales/sl.json
  src/pages/EmbedMakerPage.vue
  src/style/visualizations/main.sass
  src/visualizations/App.fs
  src/visualizations/PatientsChart.fs
  src/visualizations/ShareButton.fs
  src/visualizations/Types.fs
  src/visualizations/data/Hospitals.fs
  src/visualizations/data/Patients.fs
Labels: deploy-preview

#675 Add Sledilnik API as the OWID data source
  src/visualizations/App.fsproj
  src/visualizations/CountriesChartViz/Rendering.fs
  src/visualizations/EuropeMapChart.fs
  src/visualizations/Utils.fs
  src/visualizations/data/OurWorldInData.fs
Labels: deploy-preview

#674 Show Healthcare on Sources chart - weekly data
  src/components/FloatingMenu.vue
  src/locales/en.json
  src/locales/sl.json
  src/style/visualizations/main.sass
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/HcCasesChart.fs
  src/visualizations/Highcharts.fs
  src/visualizations/ShareButton.fs
  src/visualizations/SourcesChart.fs
  src/visualizations/Types.fs
  src/visualizations/Utils.fs
  src/visualizations/data/WeeklyStats.fs
Labels: deploy-preview

#678 Countries charts: use NIJZ data for Slovenia
  TODO.md
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/it.json
  src/locales/mk.json
  src/locales/sl.json
  src/locales/sq.json
  src/visualizations/App.fs
  src/visualizations/CountriesChartViz/Analysis.fs
  src/visualizations/CountriesChartViz/Rendering.fs
  src/visualizations/CountriesChartViz/Synthesis.fs
  src/visualizations/EuropeMapChart.fs
  src/visualizations/data/OurWorldInData.fs
  tests/Visualizations.Tests/CountriesChartTests/Grouping OWID data by countries.fs
Labels: .NET, deploy-preview, enhancement

#686 On ventilator (intubated)
  src/content/en/faq.md
  src/content/sl/faq.md
  src/locales/en.json
  src/locales/sl.json
Labels: deploy-preview

#690 Improvements in maps and country charts (+using our new OWID API)
  TODO.md
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/App.fs
  src/visualizations/CountriesChartViz/Analysis.fs
  src/visualizations/CountriesChartViz/CountrySets.fs
  src/visualizations/Types.fs
  src/visualizations/data/OurWorldInData.fs
  tests/Visualizations.Tests/CountriesChartTests/Grouping OWID data by countries.fs
Labels: .NET, WIP, deploy-preview, enhancement

#698 Cases chart: deceased in separate categories
  TODO.md
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/CasesChart.fs
Labels: .NET, WIP, deploy-preview, enhancement

#687 Bubble map
  TODO.md
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/MapChart.fs
Labels: .NET, WIP, deploy-preview, enhancement

#703 Deceased chart
  src/content/sl/faq.md
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/CasesChart.fs
  src/visualizations/DailyComparisonChart.fs
  src/visualizations/DeceasedViz/Rendering.fs
  src/visualizations/MetricsComparisonChart.fs
  src/visualizations/PatientsChart.fs
  src/visualizations/ShareButton.fs
  src/visualizations/Types.fs
Labels: .NET, deploy-preview, enhancement

#711 Deceased: added Today/ToDate charts
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/CasesChart.fs
  src/visualizations/DeceasedViz/Rendering.fs
Labels: deploy-preview

#713 Optimize twitter:* meta tags
  index.html
  index_caddy.html
  src/App.vue
Labels: deploy-preview

#717 Use youtube-nocookie.com domain to make 3rd party tracking harder
  src/components/Youtube.vue
Labels: deploy-preview

#719 Restrictions page translatable (instead of hardcoded texts)
  src/components/Notice.vue
  src/locales/en.json
  src/locales/sl.json
  src/pages/RestrictionsPage.vue
Labels: deploy-preview

#718 Add excess deaths chart
  src/components/floatingMenuDict.js
  src/content/sl/faq.md
  src/i18n.js
  src/locales/en.json
  src/locales/sl.json
  src/style/visualizations/main.sass
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/ExcessDeathsChart/Absolute.fs
  src/visualizations/ExcessDeathsChart/Chart.fs
  src/visualizations/ExcessDeathsChart/Relative.fs
  src/visualizations/ExcessDeathsChart/Types.fs
  src/visualizations/Highcharts.fs
  src/visualizations/ShareButton.fs
  src/visualizations/Types.fs
  src/visualizations/Utils.fs
  src/visualizations/data/Loader.fs
  src/visualizations/data/MonthlyDeaths.fs
Labels: deploy-preview

#720 Adds Tests per lab to Tests chart
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/it.json
  src/locales/mk.json
  src/locales/nb_NO.json
  src/locales/sl.json
  src/locales/sq.json
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/HospitalsChart.fs
  src/visualizations/PatientsChart.fs
  src/visualizations/TestsChart.fs
  src/visualizations/Utils.fs
  src/visualizations/data/Hospitals.fs
  src/visualizations/data/LabTests.fs
Labels: deploy-preview
