Repository sledilnik/website, pull requests merged in 2020-12, with the labels that each got.

#726 Switch to weekly resolution in ExcessDeathsChart
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/App.fsproj
  src/visualizations/ExcessDeathsChart/Absolute.fs
  src/visualizations/ExcessDeathsChart/Chart.fs
  src/visualizations/ExcessDeathsChart/Relative.fs
  src/visualizations/ExcessDeathsChart/Types.fs
  src/visualizations/Utils.fs
  src/visualizations/data/DailyDeaths.fs
Labels: deploy-preview

#725 Regions chart: add 7-day average for new cases
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/MetricsComparisonChart.fs
  src/visualizations/RegionsChartViz/Analysis.fs
  src/visualizations/RegionsChartViz/Rendering.fs
  src/visualizations/RegionsChartViz/Synthesis.fs
  src/visualizations/Statistics.fs
  src/visualizations/Utils.fs
  src/visualizations/data/Regions.fs
Labels: .NET, WIP, deploy-preview, enhancement

#729 Infocard: Highlight in red outdated (>36h) timestamps
  src/components/cards/InfoCard.vue
Labels: deploy-preview

#728 Infocards with 7-day average
  src/components/cards/InfoCard.vue
  src/locales/en.json
  src/locales/sl.json
  src/pages/StatsPage.vue
  src/store/patients.store.js
  src/store/stats.store.js
Labels: WIP, deploy-preview

#731 Content API
  .env.development
  .env.example
  .env.production
  .env.staging
  package.json
  src/App.vue
  src/components/FloatingMenu.vue
  src/components/LanguageSwitcher.vue
  src/components/Navbar.vue
  src/components/Notice.vue
  src/components/Posts.vue
  src/components/ReadingTime.vue
  src/components/cards/InfoCard.vue
  src/components/cards/PostTeaser.vue
  src/components/cards/PostTeaserSkeleton.vue
  src/components/charts/VegaChart.vue
  src/embed/Chart.vue
  src/index.js
  src/locales/en.json
  src/locales/sl.json
  src/main.js
  src/pages/PostSingle.vue
  src/pages/PostsPage.vue
  src/pages/StaticPage.vue
  src/pages/StatsPage.vue
  src/pages/TablesPage.vue
  src/pages/WorldStatsPage.vue
  src/plugins/index.js
  src/router.js
  src/services/api.service.js
  src/services/content-api.service.js
  src/store/health-centers.store.js
  src/store/hospitals.store.js
  src/store/index.js
  src/store/municipalities.store.js
  src/store/ostanizdrav.store.js
  src/store/patients.store.js
  src/store/posts.store.js
  src/store/stats.store.js
  src/style/main.scss
  src/style/visualizations/main.sass
  vue.config.js
  yarn.lock
Labels: WIP, deploy-preview

#747 Small bugfixes
  src/components/cards/PostTeaser.vue
  vue.config.js
Labels: deploy-preview

#751 Endpoint change for ostanizdrav
  src/store/ostanizdrav.store.js
Labels: deploy-preview

#715 MetricsCorrelation chart
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/MetricsCorrelationViz/Rendering.fs
  src/visualizations/ShareButton.fs
  src/visualizations/Types.fs
Labels: .NET, WIP, deploy-preview, enhancement

#752 Stretched links
  src/components/cards/PostTeaser.vue
Labels: deploy-preview

#753 Post font tweaks
  src/components/cards/PostTeaser.vue
  src/components/cards/PostTeaserSkeleton.vue
  src/pages/StatsPage.vue
Labels: deploy-preview

#755 Restrictions admin
  package.json
  src/components/TimeStamp.vue
  src/index.js
  src/libs/google-spreadsheet.js
  src/pages/RestrictionsPage.vue
  src/store/index.js
  src/store/restrictions.store.js
  yarn.lock
Labels: deploy-preview

#756 Search POC
  .github/workflows/pr-cleanup.yml
  .github/workflows/pr.yml
  .github/workflows/prod.yml
  .github/workflows/stage.yml
  package.json
  scripts/extract-faq.js
  src/components/Collapsable.vue
  src/content/faq.js
  src/directives.js
  src/index.js
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/it.json
  src/locales/sl.json
  src/pages/FAQPage.vue
  src/pages/RestrictionsPage.vue
  src/router.js
  yarn.lock
Labels: deploy-preview

#758 Number formatting
  src/components/cards/InfoCard.vue
  src/components/cards/PostTeaser.vue
  src/components/cards/PostTeaserSkeleton.vue
  src/filters.js
  src/i18n.js
  src/pages/PostsPage.vue
  src/pages/StatsPage.vue
  src/pages/TablesPage.vue
  src/store/tables.store.js
  src/vega/opts.js
  src/visualizations/AgeGroupsChart.fs
  src/visualizations/AgeGroupsTimelineViz/Synthesis.fs
  src/visualizations/CasesChart.fs
  src/visualizations/DailyComparisonChart.fs
  src/visualizations/DeceasedViz/Rendering.fs
  src/visualizations/EuropeMapChart.fs
  src/visualizations/HcCasesChart.fs
  src/visualizations/I18N.fs
  src/visualizations/MapChart.fs
  src/visualizations/MunicipalitiesChart.fs
  src/visualizations/PatientsChart.fs
  src/visualizations/PhaseDiagram/Chart.fs
  src/visualizations/RegionsChartViz/Rendering.fs
  src/visualizations/SourcesChart.fs
  src/visualizations/Utils.fs
Labels: deploy-preview

#760 Sources: add by Location view
  src/content/en/about.md
  src/content/sl/about.md
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/SourcesChart.fs
  src/visualizations/Types.fs
  src/visualizations/data/WeeklyStats.fs
Labels: deploy-preview

#762 Remove deceased from Active infocard
  src/components/Posts.vue
  src/components/cards/InfoCard.vue
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/it.json
  src/locales/mk.json
  src/locales/nb_NO.json
  src/locales/ru.json
  src/locales/sl.json
  src/locales/sq.json
  src/pages/StatsPage.vue
Labels: deploy-preview

#763 Summary endpoint refactor
  src/App.vue
  src/components/cards/InfoCard.vue
  src/embed/InfoCard.vue
  src/filters.js
  src/locales/en.json
  src/locales/sl.json
  src/pages/EmbedMakerPage.vue
  src/pages/StatsPage.vue
  src/store/stats.store.js
Labels: deploy-preview

#765 Tests infocard
  src/assets/svg/close-circle-percent.svg
  src/assets/svg/close-circle-plus.svg
  src/components/cards/InfoCard.vue
  src/filters.js
  src/locales/en.json
  src/locales/sl.json
  src/pages/StatsPage.vue
  src/store/stats.store.js
Labels: deploy-preview, enhancement

#769 Post fetching fixes
  .env.development
  src/content/sl/models.md
  src/pages/PostSingle.vue
  src/store/posts.store.js
Labels: deploy-preview

#771 HAT tests
  src/content/en/faq.md
  src/content/sl/faq.md
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/it.json
  src/locales/mk.json
  src/locales/nb_NO.json
  src/locales/sl.json
  src/locales/sq.json
  src/visualizations/App.fs
  src/visualizations/TestsChart.fs
Labels: deploy-preview

#772 Deceased chart - new metrics
  TODO.md
  src/locales/en.json
  src/locales/sl.json
  src/visualizations/AgeGroupsTimelineViz/Analysis.fs
  src/visualizations/AgeGroupsTimelineViz/Rendering.fs
  src/visualizations/AgeGroupsTimelineViz/Synthesis.fs
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/Colors.fs
  src/visualizations/DataAnalysis/AgeGroupsTimeline.fs
  src/visualizations/DataAnalysis/DatedTypes.fs
  src/visualizations/DataVisualization/ChartingTypes.fs
  src/visualizations/DeceasedViz/Analysis.fs
  src/visualizations/DeceasedViz/Rendering.fs
  src/visualizations/DeceasedViz/Synthesis.fs
  src/visualizations/InfectionsChart.fs
  src/visualizations/MetricsCorrelationViz/Rendering.fs
  src/visualizations/Types.fs
  tests/Visualizations.Tests/AgeGroupsTimelineTests/Calculating cases by age for day.fs
  tests/Visualizations.Tests/AgeGroupsTimelineTests/Calculating cases by age timeline.fs
  tests/Visualizations.Tests/AgeGroupsTimelineTests/Sythensizing data.fs
  tests/Visualizations.Tests/DataAnalysisTests/Working with dated arrays.fs
  tests/Visualizations.Tests/Visualizations.Tests.fsproj
Labels: .NET, WIP, deploy-preview, enhancement
