Repository sledilnik/website, pull requests merged in 2020-09, with the labels that each got.

#473 Added world map on existing chart
  examples/README.md
  examples/embed.html
  examples/embed_multi.html
  public/maps/europe.geo.json
  public/maps/world-robinson.geo.json
  public/maps/world.geo.json
  src/content/sl/faq.md
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/it.json
  src/locales/mk.json
  src/locales/sl.json
  src/locales/sq.json
  src/pages/EmbedMakerPage.vue
  src/pages/StatsPage.vue
  src/style/visualizations/main.sass
  src/visualizations/App.fs
  src/visualizations/EuropeMapChart.fs
  src/visualizations/ShareButton.fs
  src/visualizations/Types.fs
Labels: deploy-preview

#520 New color scale for map
  src/visualizations/EuropeMapChart.fs
Labels: deploy-preview

#521 Surroundings now include Italy
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/it.json
  src/locales/mk.json
  src/locales/sl.json
  src/locales/sq.json
  src/visualizations/CountriesChartViz/Rendering.fs
Labels: deploy-preview

#522 Region map
  examples/README.md
  examples/embed.html
  examples/embed_multi.html
  src/content/sl/faq.md
  src/locales/en.json
  src/locales/sl.json
  src/pages/EmbedMakerPage.vue
  src/style/visualizations/main.sass
  src/visualizations/App.fs
  src/visualizations/MapChart.fs
  src/visualizations/ShareButton.fs
  src/visualizations/Types.fs
Labels: deploy-preview

#462 Upgrade caddy from 2.0.0-rc.3 to 2.1.1
  Dockerfile
Labels: deploy-preview

#540 Started working on Countries - active cases chart
  SloCovid19Website.sln
  TODO.md
  src/locales/en.json
  src/locales/sl.json
  src/style/visualizations/main.sass
  src/visualizations/App.fs
  src/visualizations/CountriesChartViz/Analysis.fs
  src/visualizations/CountriesChartViz/Rendering.fs
  src/visualizations/CountriesChartViz/Synthesis.fs
  src/visualizations/ShareButton.fs
  src/visualizations/Types.fs
  src/visualizations/_highcharts.scss
  tests/Visualizations.Tests/CountriesChartTests/Averaging country data.fs
  tests/Visualizations.Tests/CountriesChartTests/Grouping OWID data by countries.fs
Labels: .NET, WIP, deploy-preview, enhancement

#543 Introducing FSharpLint tool to help identify sub-optimal code
  .config/dotnet-tools.json
  README.md
  SloCovid19Website.sln
  build.bat
  fsharplint-config.json
  src/visualizations/Days.fs
  src/visualizations/EuropeMapChart.fs
  src/visualizations/HCentersChart.fs
  src/visualizations/Highcharts.fs
  src/visualizations/HospitalsChart.fs
  src/visualizations/MapChart.fs
  src/visualizations/MetricsComparisonChart.fs
  src/visualizations/MunicipalitiesChart.fs
  src/visualizations/RegionsChart.fs
  src/visualizations/Utils.fs
  src/visualizations/data/HCenters.fs
  src/visualizations/data/Hospitals.fs
  src/visualizations/data/Patients.fs
  src/visualizations/data/Regions.fs
  src/visualizations/data/Stats.fs
  tests/Visualizations.Tests/AgeGroupsChartTests/Merging infections and deaths.fs
  tests/Visualizations.Tests/Date arithmetic.fs
Labels: .NET, WIP, deploy-preview, enhancement

#541 Optimization
  package-lock.json
  src/components/Footer.vue
  src/services/api.service.js
  src/store/patients.store.js
  src/store/stats.store.js
  src/visualizations/EuropeMapChart.fs
  src/visualizations/MunicipalitiesChart.fs
Labels: WIP, deploy-preview

#448 World - july update
  TODO.md
  src/visualizations/AgeGroupsChart.fs
  src/visualizations/App.fs
  src/visualizations/CountriesChartViz/Analysis.fs
  src/visualizations/CountriesChartViz/Rendering.fs
  src/visualizations/CountriesChartViz/Synthesis.fs
  src/visualizations/Utils.fs
Labels: WIP, deploy-preview

#544 Exponential growth features
  src/locales/en.json
  src/locales/hr.json
  src/locales/sl.json
  src/visualizations/Highcharts.fs
  src/visualizations/MunicipalitiesChart.fs
  src/visualizations/SpreadChart.fs
Labels: deploy-preview

#559 Intersection observer
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/IntersectionObserver.fs
  src/visualizations/IntersectionObserver.js
Labels: deploy-preview

#556 Daily Comparison Chart
  examples/embed_multi.html
  src/components/Notice.vue
  src/content/sl/faq.md
  src/locales/de.json
  src/locales/en.json
  src/locales/hr.json
  src/locales/it.json
  src/locales/mk.json
  src/locales/sl.json
  src/locales/sq.json
  src/pages/EmbedMakerPage.vue
  src/style/visualizations/main.sass
  src/visualizations/App.fs
  src/visualizations/App.fsproj
  src/visualizations/CountriesChartViz/Synthesis.fs
  src/visualizations/DailyComparisonChart.fs
  src/visualizations/I18N.fs
  src/visualizations/ShareButton.fs
  src/visualizations/Types.fs
Labels: WIP

#560 Remove dependencies
  package.json
  src/components/Footer.vue
  src/components/Navbar.vue
  src/embed/InfoCard.vue
  src/i18n.js
  src/main.js
  src/style/visualizations/main.sass
  src/visualizations/_highcharts.js
  yarn.lock
Labels: deploy-preview

#562 Made ICU darker for more contrast with hospitalized color
  src/style/visualizations/main.sass
  src/visualizations/CasesChart.fs
  src/visualizations/MetricsComparisonChart.fs
  src/visualizations/PatientsChart.fs
  src/visualizations/RatiosChart.fs
  src/visualizations/_highcharts.scss
Labels: deploy-preview

#563 fix: Fix highcharts range selector translations
  src/i18n.js
  src/visualizations/_highcharts.js
Labels: deploy-preview

#565 Change infocards layout
  src/components/Navbar.vue
  src/components/cards/InfoCard.vue
  src/pages/StatsPage.vue
  src/store/patients.store.js
  src/store/stats.store.js
  src/style/visualizations/main.sass
  src/visualizations/Highcharts.fs
Labels: WIP, deploy-preview

#566 Map labels
  src/visualizations/MapChart.fs
Labels: deploy-preview

#564 Split metrics in three groups: active, per day, to date
  src/locales/en.json
  src/locales/sl.json
  src/pages/EmbedMakerPage.vue
  src/style/visualizations/main.sass
  src/visualizations/MetricsComparisonChart.fs
  src/visualizations/RegionsChart.fs
  src/visualizations/ShareButton.fs
Labels: deploy-preview
